const allowedNames = new Set([
'hallmann','kubak','burbon9','raptusiewicz','mligeza','karolt','lpa','wayward-dreams','grigorijj','konslib',
'twisniewski333','protokaryon','przemeksz','szmulkberg','prawdawtvmowili','rymwid','mk','bartvng','mciszczon','filippal',
'engrave','rafal','mynewart','janwszolek','mtik333','radomirgs','mmmmkkkk311','avarski','klc','michuzet',
'vinece','patrycjak','fsroka','foggymeadow','natalia','kotul','wawrzyniec','wadera','czyzu','toshirskij',
'oniriusz','alicjamendrek','danxios','wierzbik','kapitanpolak','anielka','krigers','thedarzya','erykkidacki','oksana',
'romualdd','malgub','magdalenagubernat','virtus4','janhausner','marcon','justynao','edwinedwin','onurgunes','grzesiekk',
'eugenegal','przybysz','piosko','matthewmtkpl','gtg','dawidpiotrowski','andrzej520715','berthordin','ewaengel','agni',
'basementdisco','sibelius','olusiu','kamil','kbkach','bvlk','fpsf','drd97','xayu-s','anastasiia',
'oligator','dawidr','benedykt','klonowski','beatititis','pocichu','fabianmysli','kenaj','velmafia','cichociemny',
'sarmaticus','sylwir','kamil.ambrozy','kuba-madeja','becia13','drakkar','katetravel','radpie9203','arthurel','annakraska',
'bogdang','lucjuszd','innomine','lilithu','jocieprosza','maciektr','brut-to','szyszek','pawelpakula','ataraksja',
'anialavender','trzaskal','pszuklow','czwartek','alicjab','kropka','stafhalr','venti','jozefsekowski','lukaszszala',
'tosia','nari49','legun','kruppe','filipjankowski12','mwlazlo','ergorg','yavad','zabrylka','kacper94',
'michalx2008x','foqs3','madlend','kaysh','sunriced56','ptaku','charles25','westa','hiacynt','litosci',
'spiros','makaroshka','karolusia','lesiopm','grafzero','lukaszpajak','lidil','hleblazovik17','mys','korczynska',
'kjensen','marmoladka','aleksanderfurtak','blind-spot','kufelhutnika','helcim','kamdul','bowess','wstawarz','jakubadamw',
'dotu','tradipramen','adam.ski','nausika','gilkam','jtdziadosz','emiliagarbien','staryeudoksji','mededu','small.minion',
'cichoswiat','gonteix','szymon1607','panjanek','oabdelmetaal','margrzeta','mtyszczak','kacper','jfilip','arturtynski',
'apostolska','kultywacja','jakubpodsiadlo','dawidgorski','kasian','donpietro','torreamare','krag','lukmarcus','wojtyla',
'olena','mendrekola','rlip','lukij','benedyktb','dmklosowicz','filipkru','megliken','bierny','lukzloty',
'postcardsfromlbn','simoon','nieczyne','szymonwiatr','michalinamio','alkor77','caius','qmisiek','filipaz','grzesiek',
'belenzuka','htom','lulu','agus2026','kon.w0j','amadi93','borowski','pignys','santiagodepolonia','damxios',
'lukaszsroczynski','michaljp','gapjer','mkukier','elzlonkiewicz','ajanchy','jarr80','ryeman','filip223','galdun',
'maciek007','emteroo','janinachrzan','karolb','agat','herosik','elemes','szejq','rozku','kociata',
'jubed','katb359','grzegorzniemkiewicz','maciejweigt','gleblazovik17','danzis','ziemowitp','hellebelle','baro89','arek-k',
'hrabiaeryk','aga.csln','boredomnotes','michal99','deepresearch','kozieja','thomasward9','marl.boroman','magpas','olazajac',
'agullax','monikasu','global1010','pepe20','kregulec','gwyddpel','czcibor360','okolczuga','herbacianymag','pawelz01',
'rcr.app','ania','psypek','medrekola','aniaes','panna.sarna','daryna','mkubera','fundacja','ambrozykamil',
'kuba','michalrapala','mynewlife','mindmat','rycer','heinz23','madlen91','filippaluch','parkasiewicz','emigarbien',
'drwal','twszolek','sanuich','dominicus','lorenzo','klararaptusiewicz','pawianywychodzazesciany','olek','ambrozy','luc' , 'hivedocu' , 'sztukahbd'
]);
module.exports = allowedNames;